"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { tarotCards, type TarotCard } from "../tarot-data";
import "./healing-room.css";

type Room = "lobby" | "emotion" | "relationship" | "sleep" | "strength" | "records";
type RecordItem = { id:string; date:string; type:string; emotion:string; card:string; sentence:string; action:string };
const STORE = "zolacoco-healing-records-v1";
const roomOptions = [
  { id:"emotion", no:"01", title:"我想讓情緒慢下來", sub:"情緒安放室", icon:"☾" },
  { id:"relationship", no:"02", title:"我還放不下一段關係", sub:"關係放不下練習", icon:"♡" },
  { id:"sleep", no:"03", title:"我想把今天留在今晚", sub:"睡前心事收納", icon:"✦" },
  { id:"strength", no:"04", title:"我想重新找回力量", sub:"三分鐘內在練習", icon:"♢" },
] as const;
const emotionList = ["焦慮不安","委屈難過","生氣煩躁","疲累無力","混亂迷惘","說不上來"];
const relationQuestions = [
  {q:"你現在最放不下的是什麼？", options:["還想和對方重新開始","無法接受關係已經改變","對沒有答案的事情感到不甘心","害怕以後不會再遇到適合的人","我也說不清楚"]},
  {q:"當你想到這段關係時，最明顯的感受是什麼？", options:["想念","委屈","不甘心","生氣","害怕","孤單"]},
  {q:"這段關係裡，你真正想被滿足的需要是什麼？", options:["被選擇","被理解","被肯定","被陪伴","得到安全感","得到一個明確答案"]},
];
const sleepFeelings = ["焦慮","難過","生氣","委屈","疲累","混亂"];
const strengthAreas = ["感情關係","工作與方向","人際相處","金錢壓力","對自己的懷疑","生活失去動力"];
const strengthControls = ["我的回應方式","今天的時間安排","要不要繼續投入","是否向別人求助","如何照顧自己","下一個小行動"];
const powerAffirmations = ["我不必一次走完，只需要走好眼前這一步。","我可以溫柔，也可以為自己做決定。","我的感受值得被聽見，我的界線也值得被尊重。","我正在把力量，一點一點帶回自己身上。"];

function pickCard(): TarotCard { return tarotCards[Math.floor(Math.random()*tarotCards.length)] ?? tarotCards[0]; }
function dateLabel(){ return new Intl.DateTimeFormat("zh-TW",{year:"numeric",month:"long",day:"numeric"}).format(new Date()); }
function makeId(){ return globalThis.crypto?.randomUUID?.()??`heal-${Date.now()}-${Math.random().toString(36).slice(2,9)}`; }

function CardReveal({card,label}:{card:TarotCard;label:string}){
  return <div className="heal-card-reveal"><div className="heal-tarot"><img src={card.art} alt={card.scene}/><small>{card.numeral} · {card.en}</small><b>{card.name}</b></div><div><span>{label}</span><h3>{card.name}</h3><p>{card.truth}</p><aside><b>今天可以做的一個小行動</b><p>{card.action}</p></aside></div></div>
}

function StepShell({eyebrow,title,copy,step,total,onBack,children}:{eyebrow:string;title:string;copy?:string;step:number;total:number;onBack:()=>void;children:React.ReactNode}){
 return <section className="heal-sheet fade-page"><div className="heal-progress"><button onClick={onBack}>← 上一步</button><span>{step} / {total}</span></div><div className="heal-progress-line"><i style={{width:`${step/total*100}%`}}/></div><p className="heal-eyebrow">{eyebrow}</p><h2>{title}</h2>{copy&&<p className="heal-copy">{copy}</p>}{children}</section>
}

function ChoiceGrid({items,value,onChange,multi=false}:{items:string[];value:string|string[];onChange:(v:string)=>void;multi?:boolean}){
 return <div className="heal-choices">{items.map((item,i)=>{const active=multi?(value as string[]).includes(item):value===item;return <button key={item} className={active?"active":""} onClick={()=>onChange(item)}><i>{String(i+1).padStart(2,"0")}</i><span>{item}</span><b>{active?"✓":"→"}</b></button>})}</div>
}

export default function HealingRoom(){
 const [room,setRoom]=useState<Room>("lobby"); const [step,setStep]=useState(0); const [records,setRecords]=useState<RecordItem[]>([]);
 const [emotion,setEmotion]=useState(""); const [card,setCard]=useState<TarotCard|null>(null); const [sentence,setSentence]=useState("");
 const [breath,setBreath]=useState({phase:"準備好了嗎？",count:0,paused:false,finished:false});
 const [rel,setRel]=useState<string[]>(["","",""]); const [relText,setRelText]=useState("");
 const [sleep,setSleep]=useState({worry:"",feeling:"",status:"",tomorrow:""});
 const [area,setArea]=useState(""); const [controls,setControls]=useState<string[]>([]);
 const [saved,setSaved]=useState(false); const [playing,setPlaying]=useState(""); const [duration,setDuration]=useState(5);
 const audio=useRef<{ctx:AudioContext;nodes:AudioNode[];timer:number}|null>(null);
 useEffect(()=>{const load=window.setTimeout(()=>{try{setRecords(JSON.parse(localStorage.getItem(STORE)||"[]"))}catch{}},0);return()=>{clearTimeout(load);if(audio.current){audio.current.nodes.forEach(n=>{try{n.disconnect()}catch{}});clearTimeout(audio.current.timer);audio.current.ctx.close();audio.current=null}}},[]);
 useEffect(()=>{if(room!=="emotion"||step!==1||breath.paused||breath.finished)return; const phases=[["慢慢吸氣",4],["輕輕停留",2],["慢慢吐氣",6]] as const; let phase=0,cycle=breath.count; const tick=()=>{phase++; if(phase===3){phase=0;cycle++;if(cycle>=3){setBreath({phase:"呼吸完成了",count:3,paused:false,finished:true});return}} setBreath(b=>({...b,phase:`${phases[phase][0]} ${phases[phase][1]} 秒`,count:cycle})); timer=window.setTimeout(tick,phases[phase][1]*1000)}; let timer=window.setTimeout(()=>{setBreath(b=>({...b,phase:`${phases[0][0]} ${phases[0][1]} 秒`}));timer=window.setTimeout(tick,4000)},0);return()=>clearTimeout(timer)},[room,step,breath.paused,breath.finished,breath.count]);
 function go(next:Room){stopAudio();setRoom(next);setStep(0);setCard(null);setSaved(false);window.scrollTo({top:0,behavior:"smooth"})}
 function save(type:string,emo:string,text:string,action:string){const item={id:makeId(),date:dateLabel(),type,emotion:emo,card:card?.name||"",sentence:text,action};const next=[item,...records];setRecords(next);localStorage.setItem(STORE,JSON.stringify(next));setSaved(true);void fetch("/api/activity",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"healing",title:type,summary:`${emo}・${card?.name||"未抽牌"}`,details:item})})}
 function remove(id:string){if(!window.confirm("確定要刪除這一筆療癒紀錄嗎？刪除後無法復原。"))return;const next=records.filter(r=>r.id!==id);setRecords(next);localStorage.setItem(STORE,JSON.stringify(next))}
 function stopAudio(){if(audio.current){audio.current.nodes.forEach(n=>{try{n.disconnect()}catch{}});clearTimeout(audio.current.timer);audio.current.ctx.close();audio.current=null}setPlaying("")}
 function playAudio(kind:string){if(playing===kind){stopAudio();return}stopAudio();const Ctx=window.AudioContext||window.webkitAudioContext;const ctx=new Ctx();const master=ctx.createGain();master.gain.value=.14;master.connect(ctx.destination);const nodes:AudioNode[]=[master];
   if(kind==="雨夜與壁爐"||kind==="夜晚森林"){const buffer=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate);const d=buffer.getChannelData(0);const noise=new Uint32Array(d.length);crypto.getRandomValues(noise);for(let i=0;i<d.length;i++)d[i]=((noise[i]/4294967295)*2-1)*(kind==="雨夜與壁爐"?.42:.2);const src=ctx.createBufferSource();src.buffer=buffer;src.loop=true;const filter=ctx.createBiquadFilter();filter.type="lowpass";filter.frequency.value=kind==="雨夜與壁爐"?900:500;src.connect(filter);filter.connect(master);src.start();nodes.push(src,filter)}
   else {const freqs=kind==="月光鋼琴"?[261.6,329.6,392]:[174,285,432];freqs.forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=i===0?"sine":"triangle";o.frequency.value=f;g.gain.value=.14/(i+1);o.connect(g);g.connect(master);o.start();nodes.push(o,g)})}
   const timer=window.setTimeout(stopAudio,duration*60000);audio.current={ctx,nodes,timer};setPlaying(kind)}
 function restart(){setEmotion("");setSentence("");setRel(["","",""]);setRelText("");setSleep({worry:"",feeling:"",status:"",tomorrow:""});setArea("");setControls([]);setBreath({phase:"準備好了嗎？",count:0,paused:false,finished:false});go(room)}

 return <main className="healing-room"><header className="heal-nav"><Link className="heal-brand" href="/">ZOLACOCO <span>TAROT</span></Link><Link className="heal-home-link" href="/">← 最初選單</Link><button onClick={()=>go("lobby")}>療癒小房間</button><button onClick={()=>go("records")}>我的療癒紀錄 <i>{records.length}</i></button></header>
  <div className="moon-glow"/><div className="curtain left"/><div className="curtain right"/>
  {room==="lobby"&&<section className="heal-lobby fade-page"><p className="heal-eyebrow">THE HEALING ROOM · NIGHT RITUAL</p><h1>今晚，想讓心<br/>停在哪裡？</h1><p>不用急著整理好所有情緒，<br/>先選一個此刻最需要的陪伴。</p><div className="room-doors">{roomOptions.map(o=><button key={o.id} onClick={()=>go(o.id)}><i>{o.icon}</i><small>{o.no} · {o.sub}</small><b>{o.title}</b><span>輕輕走進去 <em>→</em></span></button>)}<a className="yuanchen-door" href="/healing-room/yuanchen"><i>⌑</i><small>05 · YUAN CHEN INNER HOUSE</small><b>元辰宮・內在心境探索</b><p>走進心中的房子，看看此刻的你需要整理什麼。</p><span>推開內在的門 <em>→</em></span></a></div><button className="records-link" onClick={()=>go("records")}>查看我的療癒紀錄 <span>→</span></button></section>}

  {room==="emotion"&&<>{step===0&&<StepShell eyebrow="EMOTION SANCTUARY" title="現在，哪一種情緒最靠近你？" copy="先不用解釋發生了什麼，只要認出現在的感受。" step={1} total={4} onBack={()=>go("lobby")}><ChoiceGrid items={emotionList} value={emotion} onChange={v=>{setEmotion(v);setTimeout(()=>setStep(1),220)}}/></StepShell>}
  {step===1&&<StepShell eyebrow="A THIRTY-SECOND PAUSE" title="先陪自己，呼吸三次" copy="跟著光圈慢慢呼吸，不需要做得很完美。" step={2} total={4} onBack={()=>setStep(0)}><div className={`breath-orb ${breath.paused?"paused":""}`}><div><span>{breath.phase}</span><small>第 {Math.min(breath.count+1,3)} 次呼吸</small></div></div><div className="center-actions"><button onClick={()=>setBreath(b=>({...b,paused:!b.paused}))}>{breath.paused?"繼續":"暫停"}</button><button onClick={()=>setStep(2)}>跳過</button>{breath.finished&&<button className="gold" onClick={()=>setStep(2)}>繼續抽牌 →</button>}</div></StepShell>}
  {step===2&&<StepShell eyebrow="A CARD FOR THIS MOMENT" title="抽一張此刻需要的陪伴" step={3} total={4} onBack={()=>setStep(1)}>{!card?<div className="draw-heal-card"><div className="card-back-art"/><button className="gold" onClick={()=>setCard(pickCard())}>抽一張此刻需要的陪伴</button></div>:<><CardReveal card={card} label="此刻的療癒牌"/><button className="gold next-wide" onClick={()=>setStep(3)}>把這份訊息留下來 →</button></>}</StepShell>}
  {step===3&&<StepShell eyebrow="TODAY'S HEALING CARD" title={saved?"你的今日療癒卡，已經收好了":"此刻，你最想對自己說什麼？"} step={4} total={4} onBack={()=>setStep(2)}>{!saved?<><textarea value={sentence} onChange={e=>setSentence(e.target.value)} placeholder="此刻，你最想對自己說什麼？"/><button className="gold next-wide" disabled={!sentence.trim()} onClick={()=>save("情緒安放室",emotion,sentence,card?.action||"")}>儲存今日療癒卡</button></>:<div className="today-card"><small>{dateLabel()} · ZOLACOCO HEALING</small><h3>{emotion}</h3><p>{card?.truth}</p><blockquote>「{sentence}」</blockquote><b>今天的小行動｜{card?.action}</b></div>}<div className="final-actions"><button onClick={()=>go("lobby")}>回到療癒小房間</button><button onClick={restart}>再做一次</button></div></StepShell>}</>}

  {room==="relationship"&&<>{step===0&&<section className="heal-opening fade-page"><button onClick={()=>go("lobby")}>← 回到房間</button><p className="heal-eyebrow">RELATIONSHIP JOURNAL</p><h2>有些放不下，<br/>不一定只是因為還愛著。</h2><p>也可能是遺憾、不甘心，<br/>或那個沒有被好好回應的自己。</p><button className="gold" onClick={()=>setStep(1)}>翻開這一頁 →</button></section>}{step>=1&&step<=3&&<StepShell eyebrow="RELATIONSHIP JOURNAL" title={relationQuestions[step-1].q} step={step} total={5} onBack={()=>step===1?setStep(0):setStep(step-1)}><ChoiceGrid items={relationQuestions[step-1].options} value={rel[step-1]} onChange={v=>{const n=[...rel];n[step-1]=v;setRel(n);setTimeout(()=>setStep(step+1),220)}}/></StepShell>}{step===4&&<StepShell eyebrow="RELATIONSHIP JOURNAL" title="如果今天先不追著結果跑，你最需要照顧的是什麼？" step={4} total={5} onBack={()=>setStep(3)}><textarea value={relText} onChange={e=>setRelText(e.target.value)} placeholder="把此刻想到的話，留在這一頁……"/><button className="gold next-wide" disabled={!relText.trim()} onClick={()=>{setCard(pickCard());setStep(5)}}>完成日記，抽一張關係療癒牌 →</button></StepShell>}{step===5&&card&&<StepShell eyebrow="YOUR RELATIONSHIP MESSAGE" title="這段關係，正在把你帶回自己" step={5} total={5} onBack={()=>setStep(4)}><CardReveal card={card} label="關係療癒牌"/><div className="insight-list"><article><small>我真正放不下的可能是……</small><p>{rel[0]}，以及那份「{rel[2]}」的需要。</p></article><article><small>這段關係正在提醒我的事……</small><p>{card.truth}</p></article><article><small>今天可以停止的一件事</small><p>停止反覆用同一個問題，逼自己立刻得到答案。</p></article><article><small>今天可以為自己做的一件事</small><p>{card.action}</p></article></div>{!saved&&<button className="gold next-wide" onClick={()=>save("關係放不下練習",rel[1],relText,card.action)}>收進我的療癒紀錄</button>}<div className="consult-soft"><p>如果這段關係已經反覆拉扯很久，也可以讓 Zola 陪你整理完整的關係脈絡。</p><Link href="/#consult">了解一對一塔羅諮詢 →</Link></div><div className="final-actions"><button onClick={()=>go("lobby")}>回到療癒小房間</button><button onClick={restart}>再做一次</button></div></StepShell>}</>}

  {room==="sleep"&&<>{step===0&&<section className="heal-opening sleep-opening fade-page"><button onClick={()=>go("lobby")}>← 回到房間</button><p className="heal-eyebrow">BEDTIME JOURNAL</p><h2>今天已經走到這裡了。</h2><p>剩下的事情，<br/>可以先放進今晚的抽屜。</p><button className="gold" onClick={()=>setStep(1)}>打開今晚的日記 →</button></section>}{step===1&&<StepShell eyebrow="BEDTIME JOURNAL" title="今天最讓你放不下的是什麼？" step={1} total={5} onBack={()=>setStep(0)}><textarea value={sleep.worry} onChange={e=>setSleep({...sleep,worry:e.target.value})} placeholder="不用整理得很完整，想到什麼就寫下來……"/><button className="gold next-wide" disabled={!sleep.worry.trim()} onClick={()=>setStep(2)}>下一頁 →</button></StepShell>}{step===2&&<StepShell eyebrow="BEDTIME JOURNAL" title="這件事帶給你什麼感受？" step={2} total={5} onBack={()=>setStep(1)}><ChoiceGrid items={sleepFeelings} value={sleep.feeling} onChange={v=>{setSleep({...sleep,feeling:v});setTimeout(()=>setStep(3),220)}}/></StepShell>}{step===3&&<StepShell eyebrow="BEDTIME JOURNAL" title="這件事現在可以處理嗎？" step={3} total={5} onBack={()=>setStep(2)}><ChoiceGrid items={["可以，我知道下一步","還不能，需要再等等","今天先不處理也沒關係"]} value={sleep.status} onChange={v=>{setSleep({...sleep,status:v});setTimeout(()=>setStep(4),220)}}/></StepShell>}{step===4&&<StepShell eyebrow="BEDTIME JOURNAL" title="明天醒來後，我願意先做的一件小事是什麼？" step={4} total={5} onBack={()=>setStep(3)}><textarea value={sleep.tomorrow} onChange={e=>setSleep({...sleep,tomorrow:e.target.value})} placeholder="小到明天真的做得到，就很好。"/><button className="gold next-wide" disabled={!sleep.tomorrow.trim()} onClick={()=>{setCard(pickCard());setStep(5)}}>收好日記，抽一張睡前安定牌 →</button></StepShell>}{step===5&&card&&<StepShell eyebrow="GOOD NIGHT, DEAR HEART" title="今晚不需要解決所有事情。" copy="你已經替明天留下了一個方向，現在可以先休息了。" step={5} total={5} onBack={()=>setStep(4)}><CardReveal card={card} label="睡前安定牌"/><div className="sound-panel"><h3>選一段今晚的療癒音景</h3><p>點一下播放，再點一次即可停止。</p><div className="duration-row">{[5,10,20].map(n=><button className={duration===n?"active":""} onClick={()=>{stopAudio();setDuration(n)}} key={n}>{n}分鐘</button>)}</div><div className="sound-list">{["雨夜與壁爐","月光鋼琴","水晶缽與流水","夜晚森林"].map(s=><button className={playing===s?"playing":""} onClick={()=>playAudio(s)} key={s}><i>{playing===s?"Ⅱ":"▶"}</i><span>{s}<small>{playing===s?`播放中 · ${duration} 分鐘`:"點擊播放"}</small></span></button>)}</div></div><div className={`candle-farewell ${saved?"dim":""}`}><i/><span/><p>讓燭光慢慢暗下，今天就停在這裡。</p></div><button className="gold next-wide" onClick={()=>{if(!saved)save("睡前心事收納",sleep.feeling,sleep.worry,sleep.tomorrow);stopAudio();setSaved(true)}}>收好今天，準備休息</button>{saved&&<div className="final-actions"><button onClick={()=>go("lobby")}>回到療癒小房間</button></div>}</StepShell>}</>}

  {room==="strength"&&<>{step===0&&<StepShell eyebrow="INNER STRENGTH" title="最近的你，在哪一部分最容易感到無力？" step={1} total={3} onBack={()=>go("lobby")}><ChoiceGrid items={strengthAreas} value={area} onChange={v=>{setArea(v);setTimeout(()=>setStep(1),220)}}/></StepShell>}{step===1&&<StepShell eyebrow="WHAT REMAINS YOURS" title="現在仍然在你掌握中的事情是什麼？" copy="可以選擇一個，也可以選擇好幾個。" step={2} total={3} onBack={()=>setStep(0)}><ChoiceGrid multi items={strengthControls} value={controls} onChange={v=>setControls(c=>c.includes(v)?c.filter(x=>x!==v):[...c,v])}/><button className="gold next-wide" disabled={!controls.length} onClick={()=>{setCard(pickCard());setStep(2)}}>抽一張力量牌 →</button></StepShell>}{step===2&&card&&<StepShell eyebrow="YOUR INNER STRENGTH" title="你的力量沒有消失，只是暫時被疲累蓋住了。" step={3} total={3} onBack={()=>setStep(1)}><CardReveal card={card} label="力量牌"/><div className="insight-list"><article><small>你現在仍然擁有的力量</small><p>{controls.join("、")}</p></article><article><small>需要放下的消耗</small><p>停止要求自己在還沒準備好時，就必須證明一切。</p></article><article><small>今天可以完成的一個小行動</small><p>{card.action}</p></article><article><small>一句專屬自我肯定</small><p>{powerAffirmations[tarotCards.findIndex(item=>item.id===card.id)%powerAffirmations.length]}</p></article></div><button className="gold next-wide" onClick={()=>{if(!saved)save("重新找回力量",area,controls.join("、"),card.action);setSaved(true)}}>{saved?"這份力量已經收進紀錄":"把這份力量帶回今天"}</button><div className="final-actions"><button onClick={()=>go("lobby")}>回到療癒小房間</button><button onClick={restart}>再做一次</button></div></StepShell>}</>}

  {room==="records"&&<section className="records-page fade-page"><button className="back-room" onClick={()=>go("lobby")}>← 回到療癒小房間</button><p className="heal-eyebrow">MY HEALING RECORDS</p><h1>我的療癒紀錄</h1><p>你曾經好好陪伴自己的時刻，都會留在這個裝置上。</p><a className="yuanchen-record-link" href="/healing-room/yuanchen?records=1"><span>元辰宮・內在心境紀錄</span><b>查看完整探索紀錄 →</b></a>{records.length===0?<div className="empty-record"><i>☾</i><h2>其他療癒練習還沒有紀錄</h2><p>完成任一個療癒練習後，今晚的訊息就會收藏在這裡。</p><button className="gold" onClick={()=>go("lobby")}>開始今晚的療癒</button></div>:<div className="record-list">{records.map(r=><article key={r.id}><div><small>{r.date}</small><b>{r.type}</b></div><dl><dt>當時的情緒</dt><dd>{r.emotion||"—"}</dd><dt>抽到的牌</dt><dd>{r.card||"—"}</dd><dt>寫下的句子</dt><dd>{r.sentence||"—"}</dd><dt>今日行動</dt><dd>{r.action||"—"}</dd></dl><button onClick={()=>remove(r.id)}>刪除這筆紀錄</button></article>)}</div>}</section>}
 </main>
}

declare global { interface Window { webkitAudioContext: typeof AudioContext } }
